<?php

declare(strict_types=1);

namespace SCS\Services;

use Doctrine\DBAL\Connection;
use SCS\Exception\NotFoundException;

/**
 * Loads a plugin-shipped SQL fixture into the database.
 *
 * This is the no-CLI fallback for seeding a season: the same `fixtures/*.sql`
 * files can be loaded directly via phpMyAdmin / `wp db query`, or — when the
 * host has no DB/CLI access — through the admin "Import season" button, which
 * calls this service.
 *
 * Executing raw SQL is a deliberate infra exception to the "repositories only"
 * rule (analogous to includes/Database.php::migrate(), which runs raw migration
 * SQL). The fixtures are generated by dev/fixtures/generate.py and ship in the
 * plugin, so the SQL is trusted; the only external input is the fixture *name*,
 * which is whitelisted against the shipped files (no path, no SQL body).
 */
class FixtureLoader
{
    public function __construct(
        private readonly Connection $connection,
        private readonly string $fixturesDir,
    ) {
    }

    /**
     * The fixtures available to load, each with a human-readable description
     * parsed from the file's first `-- ` comment line.
     *
     * @return list<array{name: string, description: string}>
     */
    public function availableFixtures(): array
    {
        $files = glob($this->fixturesDir . '/*.sql') ?: [];
        sort($files);

        return array_map(fn (string $path): array => [
            'name'        => basename($path, '.sql'),
            'description' => $this->firstComment($path),
        ], $files);
    }

    /**
     * Load a fixture by name, atomically. Returns post-load row counts for the
     * competition tables so the caller can confirm what was seeded.
     *
     * @return array<string, int>
     */
    public function load(string $name): array
    {
        $path = $this->resolve($name);

        $sql = file_get_contents($path);
        if ($sql === false) {
            throw new NotFoundException('Fixture could not be read.');
        }

        $statements = $this->splitStatements($sql);

        $this->connection->transactional(function (Connection $conn) use ($statements): void {
            foreach ($statements as $statement) {
                $conn->executeStatement($statement);
            }
        });

        return $this->counts();
    }

    /**
     * Resolve a fixture name to a shipped file path. The name must match an
     * available fixture's basename exactly — this rejects path separators,
     * traversal (../) and any file not shipped in the fixtures directory.
     */
    private function resolve(string $name): string
    {
        foreach ($this->availableFixtures() as $fixture) {
            if ($fixture['name'] === $name) {
                return $this->fixturesDir . '/' . $name . '.sql';
            }
        }

        throw new NotFoundException(sprintf('Unknown fixture "%s".', $name));
    }

    /**
     * Split a generated fixture into executable statements. Statements are
     * terminated by ";\n" (see dev/fixtures/generate.py), and no ";\n" appears
     * inside string values. Comment lines, blanks, and the file's own charset /
     * transaction-control statements are dropped — load() wraps everything in a
     * single transaction itself.
     *
     * @return list<string>
     */
    private function splitStatements(string $sql): array
    {
        $skip = ['SET NAMES UTF8MB4', 'START TRANSACTION', 'COMMIT'];
        $statements = [];

        foreach (explode(";\n", $sql) as $chunk) {
            $lines = [];
            foreach (explode("\n", $chunk) as $line) {
                $trimmed = trim($line);
                if ($trimmed === '' || str_starts_with($trimmed, '--')) {
                    continue;
                }
                $lines[] = $line;
            }

            $statement = trim(implode("\n", $lines));
            if ($statement === '' || in_array(strtoupper($statement), $skip, true)) {
                continue;
            }

            $statements[] = $statement;
        }

        return $statements;
    }

    private function firstComment(string $path): string
    {
        $handle = fopen($path, 'r');
        if ($handle === false) {
            return '';
        }

        try {
            while (($line = fgets($handle)) !== false) {
                $trimmed = trim($line);
                if (str_starts_with($trimmed, '--')) {
                    return trim(ltrim($trimmed, '-'));
                }
            }
        } finally {
            fclose($handle);
        }

        return '';
    }

    /** @return array<string, int> */
    private function counts(): array
    {
        $tables = [
            'seasons'   => 'wp_scs_seasons',
            'players'   => 'wp_scs_players',
            'rounds'    => 'wp_scs_rounds',
            'games'     => 'wp_scs_games',
            'snapshots' => 'wp_scs_standings_snapshots',
        ];

        $counts = [];
        foreach ($tables as $key => $table) {
            $counts[$key] = (int)$this->connection->fetchOne('SELECT COUNT(*) FROM ' . $table);
        }

        return $counts;
    }
}
